<a href="https://colab.research.google.com/github/Priya-123-kp/Assignement1-Numpy-and-Pandas/blob/main/Assignment_2_Numpy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#Create 1D Numpy Array

In [2]:
temperatures_w1 = np.array ([22.5, 25.3, 20.8, 23.4, 26.1,24.8, 21.9])

In [3]:
temperatures_w1 = np.array ([22.5, 25.3, 20.8, 23.4, 26.1,24.8, 21.9])
print("week 1 temperatures:")
print("temperatures-w1")

week 1 temperatures:
temperatures-w1


In [4]:
#Inspection and Properties

print("\n Shape of array:", temperatures_w1.shape)
print("Data type:",temperatures_w1.dtype)
print("Number of elements:",temperatures_w1.size)


 Shape of array: (7,)
Data type: float64
Number of elements: 7


# Array operations
convert celsius to Fahrenheit

In [5]:
fahrenheit = (temperatures_w1 * 9/5)+32
print("\n temperatures in Fahrenheit:")
print(fahrenheit)


 temperatures in Fahrenheit:
[72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [7]:
print(fahrenheit)

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [8]:
print("\n Maximum temperatures:", np.max(temperatures_w1))

print("\n Minimum temperatures:", np.min(temperatures_w1))

print("\n Mean temperatures:", np.mean(temperatures_w1))



 Maximum temperatures: 26.1

 Minimum temperatures: 20.8

 Mean temperatures: 23.542857142857144


#Array slicing and indexing

In [9]:
print("\n First three Temperatures:")
print(temperatures_w1[:3])

print("\n weekend Temperatures:")
print(temperatures_w1[-2:])

print("\n Middle three days:")
print(temperatures_w1[2:5])


 First three Temperatures:
[22.5 25.3 20.8]

 weekend Temperatures:
[24.8 21.9]

 Middle three days:
[20.8 23.4 26.1]


#create 2D Array

In [10]:
temperatures = np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
                        [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])

In [11]:
print(" 2D Temperature array:")
print(temperatures)

 2D Temperature array:
[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


# Inspect and Slice the 2D array

In [12]:
print("\n data type:", temperatures.dtype)
print("\n Total elements:", temperatures.size)
print("\n week 1 temperatures:")
print(temperatures[0])
print("\n week 2 temperatures:")
print(temperatures[1])
print("\n weekend  temperatures for both weeks:")
print(temperatures[:, -2:])


 data type: float64

 Total elements: 14

 week 1 temperatures:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

 week 2 temperatures:
[19.2 22.5 21.3 24.  23.5 22.8 20.1]

 weekend  temperatures for both weeks:
[[24.8 21.9]
 [22.8 20.1]]


In [13]:
import pandas as pd

In [14]:
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [15]:
print("1st Rank Mark:")
print(marks[0])
print("Top 3 Ranks:")
print(marks.loc[['Rank1', 'Rank2', 'Rank3']])
print("3rd Rank Mark:")
print(marks.iloc[2])
print("Marks Greater Than 90:")
print(marks[marks > 90])

1st Rank Mark:
95
Top 3 Ranks:
Rank1    95
Rank2    92
Rank3    89
dtype: int64
3rd Rank Mark:
89
Marks Greater Than 90:
Rank1    95
Rank2    92
dtype: int64


/tmp/ipykernel_2705/3188675746.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(marks[0])


In [16]:
marks['Rank1'] = 100
print("After Updating Rank1 Mark:")
print(marks)

After Updating Rank1 Mark:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64


In [17]:
marks = marks.drop('Rank5')
print("\nAfter Removing Last Rank:")
print(marks)


After Removing Last Rank:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64


In [18]:
cgpa = marks / 10
print("\nCGPA:")
print(cgpa)


CGPA:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [19]:
import pandas as pd

# Creating the DataFrame

In [20]:
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],

    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'
    ],

    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],

    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})


In [21]:
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [22]:
print("Transaction Data frame:")
print(transactions)

Transaction Data frame:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [23]:
print(transactions.head())

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200


In [24]:
print(transactions.tail())

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [25]:
print(transactions.shape)

(10, 4)


In [26]:
print(transactions.columns)

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')


In [27]:
print(transactions.dtypes)

TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object


In [28]:
print(transactions[['ProductCategory','Amount']])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [29]:
print("Last 3 columns:")
print(transactions.iloc[:, -3:])

Last 3 columns:
  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [30]:
print("Filtered Rows:")
filtered_data = transactions[
    (transactions['Region'] == 'North') &
    (transactions['Amount'] > 200)
]
print(filtered_data)

Filtered Rows:
   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [31]:
print(transactions['ProductCategory'].value_counts())

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [32]:
print(transactions['Region'].unique())

['North' 'South' 'East' 'West']


In [33]:
print(transactions.groupby('Region')['Amount'].mean())

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


In [34]:
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [35]:
transactions['Discount'] = transactions['Amount'] * 0.10
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0


In [36]:
transactions = transactions[transactions['TransactionID']!= 109]
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [37]:
transactions = transactions.drop('Discount', axis=1)
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
