<a href="https://colab.research.google.com/github/Priya-123-kp/Assignement1-Numpy-and-Pandas/blob/main/Mathematical_%26_Statistical_Analysis_for_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 1- Linear Algebra Implementation

In [2]:
import numpy as np

In [3]:
vector_a = np.array([2, 4, 6])
vector_b = np.array([1, 3, 5])


In [4]:
matrix_a = np.array([
    [2, 1, 3],
    [1, 0, 2],
    [4, 1, 1]
])

matrix_b = np.array([
    [1, 2, 0],
    [3, 1, 4],
    [2, 5, 1]
])

In [5]:
print("Vector A:", vector_a)
print("Vector B:", vector_b)


Vector A: [2 4 6]
Vector B: [1 3 5]


In [6]:
print("Vector Addition")
print(vector_a + vector_b)


Vector Addition
[ 3  7 11]


In [7]:
print("Vector Subtraction")
print(vector_a - vector_b)

Vector Subtraction
[1 1 1]


In [8]:
print("Dot Product")
print(np.dot(vector_a, vector_b))

Dot Product
44


In [9]:
print("Matrix Addition")
print(matrix_a + matrix_b)

Matrix Addition
[[3 3 3]
 [4 1 6]
 [6 6 2]]


In [10]:
print("Matrix Multiplication")
print(np.matmul(matrix_a, matrix_b))

Matrix Multiplication
[[11 20  7]
 [ 5 12  2]
 [ 9 14  5]]


In [11]:
det = np.linalg.det(matrix_a)
print("Determinant of Matrix A")
print(det)

Determinant of Matrix A
6.0


In [12]:
if det != 0:
    print("Inverse of Matrix A")
    print(np.linalg.inv(matrix_a))

Inverse of Matrix A
[[-0.33333333  0.33333333  0.33333333]
 [ 1.16666667 -1.66666667 -0.16666667]
 [ 0.16666667  0.33333333 -0.16666667]]


In [13]:
eigenvalues, eigenvectors = np.linalg.eig(matrix_a)

In [14]:
print("Eigenvalues")
print(eigenvalues)

Eigenvalues
[ 5.54138127 -2.         -0.54138127]


In [15]:
print("Eigenvectors")
print(eigenvectors)

Eigenvectors
[[-0.66037269 -0.42163702  0.17485589]
 [-0.3575134  -0.52704628 -0.96894315]
 [-0.66037269  0.73786479  0.17485589]]


Task 2-Probability Concepts

In [16]:
import numpy as np

In [17]:
from scipy.stats import binom

In [18]:
sales_success = [0.65, 0.35]


In [19]:
print("Probability of Successful Sales:", sales_success[0])
print("Probability of Unsuccessful Sales:", sales_success[1])

Probability of Successful Sales: 0.65
Probability of Unsuccessful Sales: 0.35


In [20]:
customer_segments = ["Premium", "Regular"]

In [21]:
segment_purchase_probability = {
    "Premium": 0.80,
    "Regular": 0.50
}


In [22]:
print("Conditional Probability")
for segment, prob in segment_purchase_probability.items():
    print(f"P(Purchase | {segment}) = {prob}")

Conditional Probability
P(Purchase | Premium) = 0.8
P(Purchase | Regular) = 0.5


In [23]:
P_A = 0.40
P_B = 0.62
P_B_given_A = 0.80

P_A_given_B = (P_B_given_A * P_A) / P_B

In [24]:
print("Bayes Theorem Result")
print("P(A|B) =", P_A_given_B)

Bayes Theorem Result
P(A|B) = 0.5161290322580646


In [25]:
n_trials = 20
success_prob = 0.65

In [26]:
binomial_samples = np.random.binomial(
    n=n_trials,
    p=success_prob,
    size=1000
)

In [27]:
print("First 10 Binomial Samples:")
print(binomial_samples[:10])

First 10 Binomial Samples:
[14 12 13 11 15 11 13 12 15 12]


In [28]:
normal_mean = 50
normal_std = 10

normal_distribution = np.random.normal(
    loc=normal_mean,
    scale=normal_std,
    size=1000
)

In [29]:
print("First 10 Normal Distribution Values")
print(normal_distribution[:10])

First 10 Normal Distribution Values
[35.97923026 50.65122772 40.60096532 55.18044124 56.11228929 48.22365814
 28.65080511 40.90761426 46.38760304 58.04668703]


In [30]:
uniform_low = 0
uniform_high = 1

uniform_distribution = np.random.uniform(
    low=uniform_low,
    high=uniform_high,
    size=1000
)

In [31]:
print("First 10 Uniform Distribution Values")
print(uniform_distribution[:10])

First 10 Uniform Distribution Values
[0.35967214 0.07461757 0.21362013 0.36037225 0.45064483 0.94815158
 0.06082316 0.16960047 0.62446845 0.34172062]


Task 3 – Descriptive Statistics

In [32]:
import numpy as np
import pandas as pd
from statistics import mode
from scipy.stats import skew, kurtosis

In [33]:
sales_data = [
    120, 135, 150, 145, 160, 155, 170, 165, 180, 175,
    190, 200, 210, 195, 185, 175, 165, 155, 145, 135
]

In [34]:
mean_value = np.mean(sales_data)

In [35]:
median_value = np.median(sales_data)

In [36]:
mode_value = mode(sales_data)

In [37]:
range_value = max(sales_data) - min(sales_data)

In [38]:
variance_value = np.var(sales_data)

In [39]:
std_value = np.std(sales_data)

In [40]:
skewness_value = skew(sales_data)

In [41]:
kurtosis_value = kurtosis(sales_data)

In [42]:
print("Mean:", mean_value)
print("Median:", median_value)
print("Mode:", mode_value)

Mean: 165.5
Median: 165.0
Mode: 135


In [43]:
print("Range:", range_value)
print("Variance:", variance_value)
print("Standard Deviation:", std_value)

Range: 90
Variance: 534.75
Standard Deviation: 23.124662159694356


In [44]:
print("Skewness:", skewness_value)
print("Kurtosis:", kurtosis_value)

Skewness: 0.030143346252736614
Kurtosis: -0.7069943289224954


In [45]:
if skewness_value > 0:
    interpretation = "Positively Skewed"
elif skewness_value < 0:
    interpretation = "Negatively Skewed"
else:
    interpretation = "Symmetric"
print("Distribution Interpretation")
print(interpretation)

Distribution Interpretation
Positively Skewed
